version: '3.8'
services:
    web:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports: 
            - "3000:3000"
        volumes:
            - ./src:/app/src
    tests:
        restart: always
        build:
            context: .
            dockerfile: Dockerfile.dev
        volumes:
            - ./src:/app/src
        command: ["npm", "run", "test"]
        